### ISSUE TITLE
Address failing mypy tests

### ISSUE THREAD

**Issue by ukmo-ccbunney** [SciTools/nc-time-axis#295]
## 📰 Custom Issue
Following a QA refresh of this repo, the following MyPy errors are being generated (and are currently being ignored in `pyproject.toml`):

```[tasklist]
### Tasks
- [ ] `attr-defined` See [check-that-attribute-exists-attr-defined](https://mypy.readthedocs.io/en/stable/error_code_list.html#check-that-attribute-exists-attr-defined)
- [ ]  `misc` See [miscellaneous-checks-misc](https://mypy.readthedocs.io/en/stable/error_code_list.html#miscellaneous-checks-misc)
- [ ]  `no-untyped-call` See [check-that-no-untyped-functions-are-called-no-untyped-call](https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-no-untyped-functions-are-called-no-untyped-call)
- [ ]  `no-untyped-def`  See [check-that-every-function-has-an-annotation-no-untyped-def](https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-every-function-has-an-annotation-no-untyped-def)
- [ ]   `unreachable` See [check-that-statement-or-expression-is-unreachable](https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-statement-or-expression-is-unreachable-unreachable)
```

These should ideally all be addressed if possible.
