### ISSUE TITLE
Address failing sp-repo-review checks

### ISSUE THREAD

**Issue by ukmo-ccbunney** [SciTools/nc-time-axis#296]
## 📰 Custom Issue
Following a QA refresh of this repo, the following Scientific Python Repo Review errors are being generated (and are currently being ignored in pyproject.toml):

```[tasklist]
### Tasks
- [ ] `PY007` Supports an easy task runner (nox or tox)
- [ ] `PP309"` Filter warnings specified
- [ ] `PC170` Uses PyGrep hooks (only needed if rST present)
```

These should be addressed and removed from this ignore list if possible.
