### ISSUE TITLE
Address failing numpydoc tests

### ISSUE THREAD

**Issue by ukmo-ccbunney** [SciTools/nc-time-axis#298]
## 📰 Custom Issue
`numpydoc` pre-commit hook is failing the following checks that need to addressed (currently they are added to an ignore list):

```[tasklist]
### Tasks
- [ ] `GL08`  No docstring
- [ ] `SS05` Summary must start with infinitive verb
- [ ] `SS06`  Summary should fit on one line
- [ ] `PR01`  Parameters not documented
- [ ] `PR06`  Wrong type used
- [ ] `PR08`  Description should start with capitol letter
- [ ] `RT01`  No Returns section found
```
